line_length:
  - 800 # warning
  - 900 # error
function_body_length:
  - 200 # warning
  - 250 # error
disabled_rules:
  - force_cast
  - trailing_whitespace
  - identifier_name
  - large_tuple
  - type_name
  - type_body_length
  - force_try
  - file_length
  - shorthand_operator
  - function_parameter_count
  - cyclomatic_complexity	
